#!/bin/bash
echo "========== usage: "
echo "deploy to 'development' server: "
echo "$ sh deploy dev "
echo " "
echo "deploy to 'staging' server: "
echo "$ sh deploy stg "
echo " "
echo "deploy to 'production' server: "
echo "$ sh deploy prod "
echo " "
echo $1

if [ "$1" = "prod" ]
then
    echo "=== Start deploying to = production ======"
    gulp clean && NODE_ENV=production gulp build && gulp scp:prod
    echo "=== End of deploying to = production ====="
fi

if [ "$1" = "dev" ]
then
    echo "=== Start deploying to = development ======"
    gulp clean && NODE_ENV=development gulp build && gulp scp:dev
    echo "=== End of deploying to = development ====="
fi

if [ "$1" = "stg" ]
then
    echo "=== Start deploying to = staging ======"
    gulp clean && NODE_ENV=staging gulp build && gulp scp:stg
    echo "=== End of deploying to = staging ====="
fi
